global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - api_url: "https://hooks.slack.com/services/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"
    channel: '#prometheus-test'
    send_resolved: false
    icon_url: https://avatars3.githubusercontent.com/u/3380462